# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asymp_var_tail <- function(RANKM, n, k, d, dimInd, x, y, dlaX, dlaY, dlaR, dlaNu, Weight, a, b) {
    .Call('copstRuc_asymp_var_tail', PACKAGE = 'copstRuc', RANKM, n, k, d, dimInd, x, y, dlaX, dlaY, dlaR, dlaNu, Weight, a, b)
}

asymp_var_tau <- function(data, d, n) {
    .Call('copstRuc_asymp_var_tau', PACKAGE = 'copstRuc', data, d, n)
}

tail_est <- function(RANKM, n, k, d, prec, x, y) {
    .Call('copstRuc_tail_est', PACKAGE = 'copstRuc', RANKM, n, k, d, prec, x, y)
}

rcpp_hello <- function() {
    .Call('copstRuc_rcpp_hello', PACKAGE = 'copstRuc')
}

