# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asymp_var_tau <- function(data, d, n) {
    .Call('copstRuc_asymp_var_tau', PACKAGE = 'copstRuc', data, d, n)
}

rcpp_hello <- function() {
    .Call('copstRuc_rcpp_hello', PACKAGE = 'copstRuc')
}

